var fs = require('fs');

function Constructor(root, port) {
	var secretPath = root + Constructor.DATA + 'secret';
	var secret = '';

	try {
		secret = fs.readFileSync(secretPath, 'utf8');
	} catch (e) {};

	return {
		root: root,
		port: port,
		data: root + Constructor.DATA,
		index: root + Constructor.INDEX,
		statics: root + Constructor.STATICS,
		favicon: Constructor.ICON_ALLSEEINGEYE,
		secrete: secret
	}
}
Constructor.ICON_ALLSEEINGEYE = 'AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAQAABILAAASCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFEAAABeAAAAXgAAAF4AAABeAAAAXgAAAF4AAABeAAAAXgAAAF4AAABeAAAAXgAAAF4AAABeAAAAXgAAAFEAAABaAAAAewAAACoAAAAqAAAAKgAAACoAAAAqAAAAKgAAACoAAAAqAAAAKgAAACoAAAAqAAAAKgAAAHoAAABbAAAAAAAAAIoAAAAhAAAAAAAAAAAAAAAHAAAAOQAAAG4AAABvAAAAPAAAAAYAAAAAAAAAAAAAACAAAACKAAAAAAAAAAAAAAAKAAAAmwAAAAYAAABKAAAARAAAAGEAAAD+AAAA/gAAAFsAAABEAAAAQAAAAAUAAACZAAAACgAAAAAAAAAAAAAAAAAAACkAAACiAAAAogAAAFEAAAB9AAAApQAAAP8AAAB2AAAAVAAAAJ4AAACgAAAAKgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXgAAAKgAAADmAAAA+AAAAPwAAAD/AAAA+AAAAOkAAACqAAAAXgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACMAAAAJQAAAFEAAACBAAAAgAAAAFIAAAAlAAAAiQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAJkAAAAEAAAAAAAAAAAAAAADAAAAlgAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAsAAAAfAAAAAAAAAAAAAAAeQAAACwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGEAAABGAAAARQAAAGEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjgAAAI0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0AAAANAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAP//AAAAAAAAAAAAABgYAACAAQAAwAMAAOAHAADwDwAA8Y8AAPifAAD8PwAA/D8AAP5/AAD//wAA//8AAA==';
Constructor.ICON_WATCH = 'AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAQAABILAAASCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwAAAHwVFRXROTk5+Dc3N/UQEBDJAAAAbgAAAAkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALx4eHuGbm5v/09PT////////////w8PD/5eXl/8VFRXTAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGiYmJujl5eX//v7+/7u7u/+6urr/vb29/8HBwf//////19fX/xgYGNoAAAAOAAAAAAAAAAAAAAAAAAAAAAICAp/ExMT//////66urv9UVFT/UVFR/1FRUf9XV1f/vr6+//////+qqqr/AAAAhQAAAAAAAAAAAAAAAAAAAAo7Ozv2rKys/8bGxv9SUlL/UVFR/1FRUf9RUVH/UVFR/1RUVP/Jycn/t7e3/yQkJOYAAAABAAAAAAAAAAAAAAA2dHR0//////+Tk5P/UVFR/1FRUf89PT3/QUFB/1FRUf9RUVH/pqam//////9YWFj/AAAAGwAAAAAAAAAAAAAAP319ff//////iYmJ/1FRUf9RUVH/Hx8f/xcXF/9RUVH/UVFR/5ubm///////YmJi/wAAACQAAAAAAAAAAAAAACBZWVn/2NjY/6ampv9RUVH/UVFR/0dHR/8HBwf/T09P/1FRUf+vr6//2NjY/0BAQPkAAAAJAAAAAAAAAAAAAAAAExMT0sXFxf/y8vL/bm5u/1FRUf9RUVH/Kioq/0BAQP97e3v/+Pj4/7+/v/8HBwe1AAAAAAAAAAAAAAAAAAAAAAAAAFJnZ2f+//////Ly8v+dnZ3/bW1t/25ubv+VlZX/+Pj4//39/f9PT0/8AAAAOQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiXFxcf/v7+//qKio////////////pKSk/+7u7v9cXFz+AAAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgISEh8nt7e/+oqKj/paWl/3Nzc/8XFxf/AAAArAAAAF0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQgAAAO0AAABJAAAAagAAAIwAAACgAAAA/wAAAJ0AAABXAAAATQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjAAAAAQAAAAAAAABuAAAASAAAAPwAAAD/AAAAbgAAAHkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATwAAAEoAAACyAAAATgAAAD8AAABLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAABzAAAAdwAAAHYAAABkAAAAAQAAAAAAAAAA8A8AAOAHAADAAwAAwAMAAIABAACAAQAAgAEAAIABAACAAwAAwAMAAMAHAADgAwAA8AMAAPEDAAD/AwAA/wMAAA==';

Constructor.DATA = '/data/';
Constructor.STATICS = '/public/lib/';
Constructor.INDEX = '/public/index.html';

module.exports = Constructor;
